"""Build a Windows x64 candidate: one runtime folder with the console runtime and the themed setup.

Run on Windows with the locked project environment plus PyInstaller (and Pillow for the icon).
No publication, signing, client installation or credential copying. The output folder holds:
  ChemDraw MCP/                      chemdraw-runtime.exe, ChemDraw MCP Setup.exe, _internal/, version.json,
                                     chemdraw-mcp.ico, Licenses/, Source/ (corresponding source sdist)
  ChemDraw-MCP-Windows-x64-<v>.zip   the folder above, for distribution
  SHA256SUMS                         checksums of the zip and of every file in the folder
"""
import argparse
import hashlib
import importlib.metadata
import io
import json
from pathlib import Path
import platform
import shutil
import subprocess
import sys
import zipfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
FOLDER = 'ChemDraw MCP'
PRODUCT = 'chemdraw-mcp-windows'

SPEC = '''# Generated by scripts/build_windows.py
from PyInstaller.utils.hooks import collect_all, collect_data_files, collect_submodules, copy_metadata

datas, binaries, hidden = [], [], []
for package in ('chemdraw_macos', 'rdkit', 'resvg_py'):
    d, b, h = collect_all(package)
    datas += d; binaries += b; hidden += h
datas += collect_data_files('mcp') + copy_metadata('chemdraw-mcp-macos')
hidden += collect_submodules('mcp.server') + ['win32com.client', 'pythoncom', 'pywintypes', 'win32api',
                                              'win32security', 'ntsecuritycon', 'tkinter', 'tkinter.filedialog']

def analysis(script):
    return Analysis([script], pathex=[ROOT], datas=datas, binaries=binaries, hiddenimports=hidden,
                    excludes=['PyInstaller', 'pytest', 'PIL'], noarchive=False)

runtime = analysis(ROOT + r'\\packaging\\desktop_runtime.py')
setup = analysis(ROOT + r'\\packaging\\windows_setup.py')
runtime_exe = EXE(PYZ(runtime.pure), runtime.scripts, [], exclude_binaries=True, name='chemdraw-runtime',
                  console=True, icon=ICON, upx=False)
setup_exe = EXE(PYZ(setup.pure), setup.scripts, [], exclude_binaries=True, name='ChemDraw MCP Setup',
                console=False, icon=ICON, upx=False)
COLLECT(runtime_exe, setup_exe, runtime.binaries, runtime.datas, setup.binaries, setup.datas,
        name=NAME, upx=False)
'''


def run(args, **kwargs):
    subprocess.run([str(arg) for arg in args], check=True, **kwargs)


def sha256(path):
    digest = hashlib.sha256()
    with open(path, 'rb') as handle:
        for block in iter(lambda: handle.read(1 << 20), b''):
            digest.update(block)
    return digest.hexdigest()


def make_icon(target):
    """Windows icon from packaging/icon.svg (resvg render, Pillow ICO container)."""
    import resvg_py
    from PIL import Image
    svg = (ROOT / 'packaging/icon.svg').read_text(encoding='utf-8')
    image = Image.open(io.BytesIO(resvg_py.svg_to_bytes(svg_string=svg, width=256, height=256)))
    image.save(target, sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)])


def notices(destination):
    destination.mkdir()
    for name in ('LICENSE', 'NOTICE', 'THIRD_PARTY_NOTICES.md'):
        shutil.copy2(ROOT / name, destination / name)
    shutil.copytree(ROOT / 'licenses', destination / 'project-upstream')
    for dist in importlib.metadata.distributions():
        for file in dist.files or []:
            if any(word in str(file).lower() for word in ('license', 'copying', 'notice')) and '.dist-info/' in str(file):
                source = Path(dist.locate_file(file))
                if source.is_file():
                    target = destination / dist.metadata['Name'] / Path(*Path(str(file)).parts[1:])
                    target.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(source, target)
    python_license = Path(sys.base_prefix) / 'LICENSE.txt'  # covers the redistributed interpreter and stdlib
    if not python_license.is_file():
        raise RuntimeError('Locate the bundled interpreter license before distribution')
    shutil.copy2(python_license, destination / 'Python-LICENSE.txt')


def drop_build_machine_records(folder):
    """Remove pip's direct_url.json: an editable install records the build checkout's absolute path."""
    removed = sorted(folder.rglob('*.dist-info/direct_url.json'))
    for path in removed:
        path.unlink()
    return removed


def require_no_build_paths(folder, roots):
    """Refuse a candidate in which any file still names a build-machine directory."""
    markers = set()
    for root in roots:
        root = Path(root)
        for text in (str(root), root.as_posix(), json.dumps(str(root))[1:-1]):
            markers.add(text.encode('utf-8'))
            markers.add(text.encode('utf-16-le'))
    for path in sorted(folder.rglob('*')):
        if path.is_file():
            data = path.read_bytes()
            if any(marker in data for marker in markers):
                raise RuntimeError(f'Candidate names a build machine path in {path.relative_to(folder).as_posix()}')


def build(destination, version, uv):
    if platform.system() != 'Windows' or platform.machine() not in ('AMD64', 'x86_64'):
        raise RuntimeError('Build on 64-bit Windows')
    from chemdraw_macos.windows_install import runtime_version  # validates the folder after the build
    destination = destination.resolve()
    destination.mkdir(parents=True, exist_ok=False)
    icon = destination / 'chemdraw-mcp.ico'
    make_icon(icon)
    spec = destination / 'chemdraw-mcp-windows.spec'
    spec.write_text(f'ROOT = {str(ROOT)!r}\nICON = {str(icon)!r}\nNAME = {FOLDER!r}\n' + SPEC, encoding='utf-8')
    run([sys.executable, '-m', 'PyInstaller', '--noconfirm', '--distpath', destination / 'dist',
         '--workpath', destination / 'work', spec], cwd=ROOT)
    folder = destination / 'dist' / FOLDER
    shutil.copy2(icon, folder / 'chemdraw-mcp.ico')
    notices(folder / 'Licenses')
    run([uv, 'build', '--sdist', '--out-dir', folder / 'Source', ROOT])
    sdist = next((folder / 'Source').glob('*.tar.gz'))
    (folder / 'version.json').write_text(json.dumps({
        'product': PRODUCT, 'version': version, 'python': platform.python_version(),
        'source_sdist': sdist.name, 'source_sha256': sha256(sdist)}, indent=2) + '\n', encoding='utf-8')
    if runtime_version(folder) != version:
        raise RuntimeError('version.json does not describe the built runtime')
    check = subprocess.run([str(folder / 'chemdraw-runtime.exe'), '--self-check'], capture_output=True, text=True,
                           timeout=300, cwd=destination, stdin=subprocess.DEVNULL)
    print(check.stdout.strip())
    if check.returncode:
        raise RuntimeError('Runtime self-check failed: ' + check.stderr[-2000:])
    drop_build_machine_records(folder)
    require_no_build_paths(folder, [ROOT, destination, Path.home()])
    private = [p for p in folder.rglob('*') if p.name.endswith(('.connection.json', '.chemdrawaddin'))]
    if private or any(p.is_symlink() for p in folder.rglob('*')):
        raise RuntimeError('Candidate must contain no private add-in files or links')
    archive = destination / f'ChemDraw-MCP-Windows-x64-{version}.zip'
    with zipfile.ZipFile(archive, 'w', zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for path in sorted(folder.rglob('*')):
            if path.is_file():
                zf.write(path, Path(FOLDER) / path.relative_to(folder))
    with zipfile.ZipFile(archive) as zf:
        if zf.testzip() is not None:
            raise RuntimeError('Archive CRC check failed')
    lines = [f'{sha256(archive)}  {archive.name}']
    lines += [f'{sha256(p)}  {FOLDER}/{p.relative_to(folder).as_posix()}' for p in sorted(folder.rglob('*')) if p.is_file()]
    (destination / 'SHA256SUMS').write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
    print(archive)
    return archive


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('destination', type=Path, help='New build directory')
    parser.add_argument('--version', required=True, help='Candidate version, e.g. 0.10.0rc22-win.1')
    parser.add_argument('--uv', default='uv', help='uv executable for the corresponding source sdist')
    args = parser.parse_args()
    build(args.destination, args.version, args.uv)
